name = "syncgrade-web"
compatibility_date = "2026-03-27"
main = "src/worker/index.ts"

[assets]
directory = "dist"

[[d1_databases]]
binding = "syncgrade"
database_name = "syncgrade"
database_id = "2553de85-8780-4f67-b687-b90ae1b3e20e"
